### ISSUE TITLE
테스트 환경에서 css-modules className으로 적용한 스타일을 인식하지 못하는 문제

### ISSUE THREAD

**Issue by mangmuse** [f-lab-edu/fit-planner#5]
테스트 대상 컴포넌트는 BottomNavBarItem 입니다

```tsx
// jest.config.ts

import nextJest from "next/jest";

const createJestConfig = nextJest({
  dir: "./",
});

const customJestConfig = {
  moduleFileExtensions: ["js", "jsx", "ts", "tsx", "css", "less"],
  setupFilesAfterEnv: ["<rootDir>/jest.setup.ts"],
  testEnvironment: "jsdom",
  clearMocks: true,
  moduleNameMapper: {
    "^next/image$": "<rootDir>/src/__mocks__/next/Image.tsx",
    "\\.(css|less)$": "identity-obj-proxy",
  },
};

export default createJestConfig(customJestConfig);

```

```tsx
// BottomNavBarItem.tsx

import Image from "next/image";
import Link from "next/link";
import styles from "@/components/styles/BottomNavBarItem.module.css";

const BottomNavBarItem = ({
  path,
  icon,
  activeIcon,
  label,
  isActive,
}: {
  path: string;
  icon: string;
  activeIcon: string;
  label: string;
  isActive: boolean;
}) => {
  return (
    <Link href={path}>
      <li className={styles.navBarButton} data-active={isActive}>
        <Image
          className={styles.navBarButtonIcon}
          src={isActive ? activeIcon : icon}
          alt={label}
        />
        <span>{label}</span>
      </li>
    </Link>
  );
};

export default BottomNavBarItem;

```

```css
// BottomNavBarItem.module.css

.navBarButton {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: center;
  font-size: 12px;
  cursor: pointer;
  color: var(--color-text-muted);

  &[data-active="true"] {
    /* color: var(--color-primary);
     */
    color: #b0eb5f;
  }
}

.navBarButtonIcon {
  margin-bottom: 4px;
}

```

```tsx
// BottomNavBarItem.spec.tsx

import { act, render, RenderResult, screen } from "@testing-library/react";
import BottomNavBarItem from "../BottomNavBar/BottomNavBarItem";
import home from "public/bottom-navbar/home.svg";
import activeHome from "public/bottom-navbar/active_home.svg";
import mockRouter from "next-router-mock";
import userEvent from "@testing-library/user-event";
import { MemoryRouterProvider } from "next-router-mock/MemoryRouterProvider";

...

  it("props로 전달받은 isActive가 true인 경우 텍스트의 색상이 메인색상으로 변경된다", () => {
    renderBottomNavBarItem(true);

    // const text = screen.getByText("홈") as HTMLSpanElement;
    const li = screen.getByRole("listitem");

    console.log(li.style, li.className);
    console.log(document.documentElement.innerHTML);
    expect(li).toHaveStyle("color: #b0eb5f");
  });
```

```bash
 console.log
    CSSStyleDeclaration {
      _values: {},
      _importants: {},
      _length: 0,
      _onChange: [Function (anonymous)]
    } navBarButton

      at Object.log (src/components/tests/BottomNavBarItem.spec.tsx:62:13)

  console.log
    <head></head><body><div><a href="/home"><li class="navBarButton" data-active="true"><img alt="홈" src="/mock-active-home.jpg"><span>홈</span></li></a></div></body>

      at Object.log (src/components/tests/BottomNavBarItem.spec.tsx:63:13)

 FAIL  src/components/tests/BottomNavBarItem.spec.tsx
  isActive
    ✕ props로 전달받은 isActive가 true인 경우 텍스트의 색상이 메인색상으로 변경된다 (55 ms)
  label
    ✓ props로 전달받은 label이 텍스트로 출력된다 (4 ms)
    ✓ props로 전달받은 label이 이 아이콘 이미지의 alt로 지정된다 (7 ms)

  ● isActive › props로 전달받은 isActive가 true인 경우 텍스트의 색상이 메인색상으로 변경된다

    expect(element).toHaveStyle()

    - Expected

    - color: rgb(176, 235, 95);

      62 |     console.log(li.style, li.className);
      63 |     console.log(document.documentElement.innerHTML);
    > 64 |     expect(li).toHaveStyle("color: #b0eb5f");
         |                ^
      65 |   });
      66 |
      67 |   // it("props로 전달받은 itActive가 true인 경우 icon 대신 activeIcon을 사용한다", () => {

      at Object.toHaveStyle (src/components/tests/BottomNavBarItem.spec.tsx:64:16)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        1.269 s
Ran all test suites related to changed files.

Watch Usage: Press w to show more.
```

위 테스트에서 li의 style에 `color: #b0eb5f` 가 있을것을 기대했지만 li에는 지정된 색상이 없어 테스트에 실패하였고 해당 부분을 console에 출력해보니 클래스명 해싱이 안되어있고 스타일도 없는것을 확인했습니다

```html
 // BottomNavBarItem.tsx
 
 <li
        className={styles.navBarButton}
        data-active={isActive}
        style={{ color: "#b0eb5f" }}
      >
```

```bash
  console.log
    CSSStyleDeclaration {
      '0': 'color',
      _values: { color: 'rgb(176, 235, 95)' },
      _importants: { color: undefined },
      _length: 1,
      _onChange: [Function (anonymous)]
    } navBarButton

      at Object.log (src/components/tests/BottomNavBarItem.spec.tsx:62:13)

  console.log
    <head></head><body><div><a href="/home"><li class="navBarButton" data-active="true" style="color: rgb(176, 235, 95);"><img alt="홈" src="/mock-active-home.jpg"><span>홈</span></li></a></div></body>

      at Object.log (src/components/tests/BottomNavBarItem.spec.tsx:63:13)

 PASS  src/components/tests/BottomNavBarItem.spec.tsx
  ✓ 클릭 시 props로 전달받은 path 경로로 이동한다 (47 ms)
  isActive
    ✓ props로 전달받은 isActive가 true인 경우 텍스트의 색상이 메인색상으로 변경된다 (26 ms)
    ✓ props로 전달받은 itActive가 true인 경우 icon 대신 activeIcon을 사용한다 (5 ms)
    ✓ itActive가 false인 경우 텍스트의 색상이 회색이다
    ✓ itActive가 false인 경우 icon을 이미지 src로 사용한다
  label
    ✓ props로 전달받은 label이 텍스트로 출력된다 (2 ms)
    ✓ props로 전달받은 label이 이 아이콘 이미지의 alt로 지정된다 (2 ms)

Test Suites: 1 passed, 1 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        1.177 s
Ran all test suites related to changed files.

Watch Usage: Press w to show more.

```

또한 이 문제는 인라인으로 스타일을 지정할경우 문제없이 스타일을 확인할 수 있으며 테스트도 성공합니다

**Comment by f-lab-kevin** [comment]
이 코드만 보았을 땐 toHaveStyle이라는 함수를 통해 스타일 적용을 확인하려고 시도하는 방향이 바뀌어야되지 않나 싶네요
toHaveStyle은 css 프로퍼티 인자를 기반으로 확인하는 API이기 때문에 클래스로 적용된 스타일을 확인하는 방향 관점에서는 목적에 맞지 않을것 같습니다
getComputedStyle 같은 속성을 통해 최종 적용된 스타일을 가져와서 이퀄 체크를 해보시죠
css의 computedStyle 개념도 같이 확인해보시면 좋을것 같구요!
